name: cll-time_course
description: CLL ibrutinib time course
username: arendeiro
email: arendeiro@cemm.oeaw.ac.at
metadata:
  output_dir: /scratch/lab_bock/shared/projects/cll-time_course
  results_subdir: data
  submission_subdir: runs
  pipelines_dir: /home/arendeiro/workspace/pipelines
  sample_annotation: annotation.csv
  merge_table: merge_table.csv

data_sources:
  bsf: "/scratch/lab_bsf/samples/{flowcell}/{flowcell}_{lane}_samples/{flowcell}_{lane}#{BSF_name}.bam"
  bsf_seq: "/data/groups/lab_bsf/sequences/{flowcell}/fastq_path/{lane}/{BSF_name}"
  nik_seq: "/scratch/lab_bock/shared/projects/cll-time_course/data/cellranger/{lane}/{BSF_name}"

sample_attributes:
  - "sample_name"
  - "patient_id"
  - "timepoint"
  - "cell_type"
  - "compartment"
  - "sex"
  - "ighv_mutation"
  - "ighv_homology"
  - "p53_mutation"
  - "cd38_expression"
  - "binet_stage"
  - "number_of_prior_treatments"
  - "ttft"
  - "response_at_120"
  - "response"
  - "cell_number"
  - "batch"
  - "good_batch"
numerical_attributes:
  - 'ighv_homology'
  - 'number_of_prior_treatments'
  - 'ttft'
  - 'response_at_120'
group_attributes:
  - "patient_id"
  - "timepoint"
  - "cell_type"
  - "compartment"
  - 'sex'
  - 'ighv_mutation'
  - 'ighv_homology'
  - 'p53_mutation'
  - 'cd38_expression'
  - 'binet_stage'
  - 'number_of_prior_treatments'
  - 'ttft'
  - 'response_at_120'
  - "batch"
  - "good_batch"

genomes:
  human: hg19

compute_packages:
  # CeMM configuration
  submission_template: slurm_template.sub
  submission_command: sbatch

trackhubs:
  trackhub_dir: /data/groups/lab_bock/public_html/arendeiro/cll-time_course/
  url: http://biomedical-sequencing.at/bocklab/arendeiro/cll-time_course
